index:
    path: /
    controller: App\Controller\DefaultController::index

books:
    path: /books-list
    controller: App\Controller\DefaultController::books

books_generate:
    path: /book-generator
    controller: App\Controller\DefaultController::booksGenerator
